name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      working-directory: data-store
      run: npm install -g yarn
 
    - name: Install dependencies
      working-directory: data-store
      run: yarn install

    - name: Build the package and check code syntax and unit tests
      working-directory: data-store
      run: |
        yarn build
        yarn lint
        yarn test
